# Generated by Django 4.0.5 on 2022-09-07 10:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLTLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('Loan_Type', models.CharField(default=0, max_length=50)),
                ('PaymentDue_amount', models.FloatField(default='$', verbose_name='Minimum Due amount')),
                ('Due_date', models.DateField(default=datetime.date(2022, 9, 27), verbose_name='Due Date')),
                ('SLT_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlT_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_date', models.DateField(default=datetime.date(2022, 9, 27), verbose_name='Due Date')),
                ('current_balace', models.FloatField(default='$', verbose_name='Minimum Due amount')),
                ('Estimated_spend', models.FloatField(default='$', verbose_name='Minimum Due amount')),
                ('shortage', models.FloatField(default=0)),
                ('days_more', models.IntegerField(default=0)),
                ('SLT_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
