# Generated by Django 4.0.5 on 2022-09-08 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slt_summary',
            name='Due_date',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='sltloan',
            name='Due_date',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Due Date'),
        ),
    ]
