# Generated by Django 4.0.5 on 2022-09-28 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='auto_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 18), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='catche_bill_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 28), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creditcard_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 18), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='loanType',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='loan_eligiblity_flag',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='mortgage_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 18), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='paycheck_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 18), null=True),
        ),
    ]
