# Generated by Django 4.0.5 on 2022-11-10 10:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_alter_customer_loan_decision_attrs_auto_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='auto_due_date',
            field=models.CharField(blank=True, db_index=True, default=datetime.date(2022, 11, 30), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='catche_bill_due_date',
            field=models.CharField(blank=True, db_index=True, default=datetime.date(2022, 12, 10), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creditcard_due_date',
            field=models.CharField(blank=True, db_index=True, default=datetime.date(2022, 11, 30), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='mortgage_due_date',
            field=models.CharField(blank=True, default=datetime.date(2022, 11, 30), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='paycheck_date',
            field=models.CharField(blank=True, db_index=True, default=datetime.date(2022, 11, 30), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_history',
            name='Due_date',
            field=models.CharField(blank=True, default=datetime.date(2022, 11, 30), max_length=50, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='Due_date',
            field=models.CharField(blank=True, default=datetime.date(2022, 11, 30), max_length=50, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='current_paydate',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='fund_return_date',
            field=models.CharField(default=datetime.date(2022, 11, 20), max_length=50, verbose_name='Fund return Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='next_Duedate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='current_paydate',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='fund_return_date',
            field=models.CharField(default=datetime.date(2022, 12, 20), max_length=50, verbose_name='Fund return Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='next_Duedate',
            field=models.CharField(blank=True, default=datetime.date(2022, 12, 10), max_length=50, null=True, verbose_name='Due Date'),
        ),
    ]
