# Generated by Django 4.0.5 on 2022-09-28 22:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loan', '0002_alter_customer_loan_decision_attrs_auto_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='auto_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='catche_bill_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 29), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creditcard_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='mortgage_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='paycheck_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.CreateModel(
            name='PaymentSummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Type', models.CharField(default=0, max_length=50)),
                ('PaymentDue_amount', models.FloatField(verbose_name='Minimum Due amount')),
                ('Planned_payment', models.FloatField(verbose_name='Your Planned Payment')),
                ('user_payment', models.FloatField(verbose_name='Your Payment')),
                ('catche_fund', models.FloatField(default=0, verbose_name='Fund From Catche')),
                ('fund_return_date', models.DateField(default=datetime.date(2022, 11, 8), verbose_name='Fund return Date')),
                ('fund_return_amount', models.FloatField(default=0)),
                ('current_paydate', models.DateField(default=django.utils.timezone.now)),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Type', models.CharField(default=0, max_length=50)),
                ('PaymentDue_amount', models.FloatField(verbose_name='Minimum Due amount')),
                ('Planned_payment', models.FloatField(verbose_name='Your Planned Payment')),
                ('user_payment', models.FloatField(verbose_name='Your Payment')),
                ('catche_fund', models.FloatField(default=0, verbose_name='Fund From Catche')),
                ('fund_return_date', models.DateField(default=datetime.date(2022, 11, 8), verbose_name='Fund return Date')),
                ('fund_return_amount', models.FloatField(default=0)),
                ('current_paydate', models.DateField(default=django.utils.timezone.now)),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Type', models.CharField(default=0, max_length=50)),
                ('PaymentDue_amount', models.FloatField(default='$', verbose_name='Minimum Due amount')),
                ('Due_date', models.DateField(default=datetime.date(2022, 10, 29), verbose_name='Due Date')),
                ('days_more', models.IntegerField(default=0)),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
