# Generated by Django 4.0.5 on 2022-11-16 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loan', '0003_alter_customer_loan_decision_attrs_upload_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_loan_decision_attrs',
            name='Upload_statement',
        ),
        migrations.RemoveField(
            model_name='user_uploaded_statments',
            name='id',
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='CreatedTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='EventID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='InsUpdFlag',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='UpdateTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='creDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='creUser',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='user_uploaded_statments',
            name='Sugan_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='loan_eligiblity_flag',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user_uploaded_statments',
            name='Upload_statement',
            field=models.FileField(null=True, upload_to='uploads/loanstatements/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
