# Generated by Django 4.0.5 on 2022-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0003_alter_slt_summary_due_date_alter_sltloan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sltloan',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sltloan',
            name='acount_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
