# Generated by Django 4.0.5 on 2022-11-11 07:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0003_alter_customer_loan_decision_attrs_auto_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_loan_decision_attrs',
            name='Upload_statement',
            field=models.FileField(null=True, upload_to='uploads/loanstatements/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='auto_due_date',
            field=models.CharField(blank=True, db_index=True, default='2022-12-01', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='catche_bill_due_date',
            field=models.CharField(blank=True, db_index=True, default=datetime.date(2022, 12, 11), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creditcard_due_date',
            field=models.CharField(blank=True, db_index=True, default='2022-12-01', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='mortgage_due_date',
            field=models.CharField(blank=True, default='2022-12-01', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='paycheck_date',
            field=models.CharField(blank=True, db_index=True, default='2022-12-01', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_history',
            name='Due_date',
            field=models.CharField(blank=True, default='2022-12-01', max_length=50, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='Due_date',
            field=models.CharField(blank=True, default='2022-12-01', max_length=50, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='fund_return_date',
            field=models.CharField(default='2022-11-21', max_length=50, verbose_name='Fund return Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='fund_return_date',
            field=models.CharField(default=datetime.date(2022, 12, 21), max_length=50, verbose_name='Fund return Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='next_Duedate',
            field=models.CharField(blank=True, default=datetime.date(2022, 12, 11), max_length=50, null=True, verbose_name='Due Date'),
        ),
    ]
