# Generated by Django 4.0.5 on 2022-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0003_alter_customer_loan_decision_attrs_auto_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsummary',
            name='CreatedTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='InsUpdFlag',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='UpdateTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='creDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='creUser',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='CreatedTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='InsUpdFlag',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='UpdateTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='creDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='creUser',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
