# Generated by Django 4.0.5 on 2022-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0004_paymentsummary_createdts_paymentsummary_insupdflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsummary',
            name='is_paid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummaryhistory',
            name='is_paid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creUser',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='creUser',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='creUser',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
