# Generated by Django 4.0.5 on 2022-09-09 08:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loan', '0004_sltloan_address_sltloan_acount_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlT_Payment_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_Type', models.CharField(default=0, max_length=50)),
                ('PaymentDue_amount', models.FloatField(verbose_name='Minimum Due amount')),
                ('Planned_payment', models.FloatField(verbose_name='Your Planned Payment')),
                ('user_payment', models.FloatField(verbose_name='Your Payment')),
                ('cathe_fund', models.FloatField(verbose_name='Fund From Cathe')),
                ('fund_return_date', models.DateField(default=datetime.date(2022, 10, 9), verbose_name='Fund return Date')),
                ('SLT_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
