# Generated by Django 4.0.5 on 2022-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0005_slt_payment_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='slt_payment_summary',
            name='fund_return_amount',
            field=models.FloatField(default=0),
        ),
    ]
