# Generated by Django 4.0.5 on 2022-09-30 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loan', '0005_paymentsummary_is_paid_paymentsummaryhistory_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='auto_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='catche_bill_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 30), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='creditcard_due_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='mortgage_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='customer_loan_decision_attrs',
            name='paycheck_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2022, 10, 20), null=True),
        ),
        migrations.AlterField(
            model_name='customerloan',
            name='Due_date',
            field=models.DateField(default=datetime.date(2022, 10, 30), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='fund_return_date',
            field=models.DateField(default=datetime.date(2022, 11, 9), verbose_name='Fund return Date'),
        ),
        migrations.AlterField(
            model_name='paymentsummaryhistory',
            name='fund_return_date',
            field=models.DateField(default=datetime.date(2022, 11, 9), verbose_name='Fund return Date'),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('loan_type', models.CharField(default=0, max_length=50)),
                ('account_number', models.CharField(default=0, max_length=50)),
                ('Due_date', models.DateField(verbose_name='Due Date')),
                ('Payment_address', models.CharField(default=0, max_length=50)),
                ('delivery_option', models.CharField(default=0, max_length=50)),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
