# Generated by Django 4.0.5 on 2022-11-16 06:12

import Loan.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_loan_decision_attrs',
            name='Upload_statement',
            field=models.FileField(null=True, upload_to=Loan.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
