# Generated by Django 4.0.5 on 2022-06-07 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_name', models.CharField(max_length=30, verbose_name='Enter Your Name:')),
                ('Cus_email', models.EmailField(max_length=254, verbose_name='E-mail Id :')),
                ('Cus_phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')], verbose_name='Phone Number :')),
                ('Cus_password', models.CharField(max_length=50, verbose_name='Enter Password')),
            ],
        ),
    ]
