# Generated by Django 4.0.5 on 2022-09-27 11:22

import User_Account.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('log_outtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(db_index=True, default=None, max_length=50)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True, validators=[User_Account.models.WhitelistEmailValidator(whitelist=['gmail.com', 'yahoo.com', 'hotmail.com'])])),
                ('phone_number', models.CharField(help_text="Phone number must be entered in the format:'+1234567890'", max_length=15, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3})?,?\\s?\\d{8,13}$', message="Phone number must be entered in the format:'+99999'.upto 15 digits allowed.")])),
                ('catche_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
