# Generated by Django 4.0.5 on 2022-11-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_history',
            name='id',
        ),
        migrations.AddField(
            model_name='login_history',
            name='CreatedTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='login_history',
            name='Eventid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='login_history',
            name='InsUpdFlag',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='login_history',
            name='UpdateTs',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='login_history',
            name='catche_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='login_history',
            name='creDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='login_history',
            name='creUser',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='login_history',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='current_login',
            fields=[
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(db_index=True, default=None, max_length=50)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('Eventid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('log_outtime', models.DateTimeField(blank=True, null=True)),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
