# Generated by Django 4.0.5 on 2022-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0003_catche_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catche_wishlist',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
