# Generated by Django 4.0.5 on 2022-11-03 07:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatcheSubscriptionlookup',
            fields=[
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(db_index=True, default=None, max_length=50)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('Subscription_Type', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('SubscriptionName', models.CharField(blank=True, max_length=50)),
                ('SubscriptionAmount', models.FloatField(default=0)),
                ('Subscription_limit', models.FloatField(default=0)),
                ('Description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(db_index=True, default=None, max_length=50)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('SubscriptionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SubscriptionStartDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('SubscriptionEndDate', models.DateTimeField(db_index=True, default=datetime.date(2022, 12, 3))),
                ('SubscriptionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.catchesubscriptionlookup')),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('creUser', models.CharField(db_index=True, default=None, max_length=50)),
                ('CreatedTs', models.DateTimeField(db_index=True, null=True)),
                ('UpdateTs', models.DateTimeField(db_index=True, null=True)),
                ('creDate', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('InsUpdFlag', models.CharField(db_index=True, max_length=50, null=True)),
                ('EventID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Subscription_Reason', models.CharField(blank=True, max_length=50)),
                ('SubscriptionStartDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('SubscriptionEndDate', models.CharField(db_index=True, default=datetime.date(2022, 12, 3))),
                ('Refund_Amount', models.FloatField(default=0)),
                ('SubscriptionID', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='membership.subscription')),
                ('SubscriptionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.catchesubscriptionlookup')),
                ('catche_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
