# Generated by Django 4.0.5 on 2022-11-08 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionEndDate',
            field=models.DateTimeField(db_index=True, default=datetime.date(2022, 12, 9)),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='SubscriptionEndDate',
            field=models.DateField(db_index=True, default=datetime.date(2022, 12, 9)),
        ),
    ]
