# Generated by Django 4.0.5 on 2022-09-28 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_subscription_subscriptionenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionEndDate',
            field=models.DateTimeField(db_index=True, default=datetime.date(2022, 10, 29)),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='SubscriptionEndDate',
            field=models.DateField(db_index=True, default=datetime.date(2022, 10, 29)),
        ),
    ]
