# Generated by Django 4.0.5 on 2022-11-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_subscription_subscriptionenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionEndDate',
            field=models.DateTimeField(db_index=True, default=datetime.date(2022, 12, 11)),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='SubscriptionEndDate',
            field=models.CharField(db_index=True, default=datetime.date(2022, 12, 11), max_length=50),
        ),
    ]
